"""Generate a Markdown reference of every scale in `SCALES`, grouped by
size and shown as degree labels (1 ♭2 3 …). Output: docs/scales.md.

Run: python3 examples/list_scales.py
"""
import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', 'src'))

from fretboard import SCALES, scale_degree_labels


SIZE_LABELS = {
    5: 'Pentatonic (5 notes)',
    6: 'Hexatonic (6 notes)',
    7: 'Heptatonic (7 notes)',
    8: 'Octatonic (8 notes)',
    9: 'Nonatonic (9 notes)',
    12: 'Chromatic (12 notes)',
}


def main():
    out_path = os.path.join(os.path.dirname(__file__), '..', 'docs', 'scales.md')
    os.makedirs(os.path.dirname(out_path), exist_ok=True)

    by_size = {}
    for name, intervals in SCALES.items():
        by_size.setdefault(len(intervals), []).append(name)

    lines = [
        '# Scales reference',
        '',
        f'{len(SCALES)} scales total, grouped by size. Each row shows the',
        'scale name and its interval pattern as scale-degree labels',
        '(1, ♭2, 2, ♭3, 3, 4, ♯4, 5, ♯5, 6, ♭7, 7).',
        '',
        'Many scales are cross-cultural aliases for the same interval set',
        '(e.g. `phrygian_dominant` = `maqam_hijaz` = `jewish_ahava_raba`;',
        '`double_harmonic` = `maqam_hijaz_kar` = `raga_bhairav`). They are',
        'all kept so you can search by Western, raga, maqam, or qenet name.',
        '',
        'This file is auto-generated by `examples/list_scales.py`.',
        '',
    ]

    # Compute column widths globally so all tables align nicely.
    max_name = max(len(n) for n in SCALES)
    max_deg = max(len(' '.join(scale_degree_labels(n))) for n in SCALES)
    name_w = max(max_name, len('scale'))
    deg_w = max(max_deg, len('degrees'))

    for size in sorted(by_size):
        heading = SIZE_LABELS.get(size, f'{size}-note')
        names = sorted(by_size[size])
        lines.append(f'## {heading}  —  {len(names)} entries')
        lines.append('')
        lines.append('```')
        lines.append(f'{"scale".ljust(name_w)}   {"degrees".ljust(deg_w)}')
        lines.append('-' * (name_w + 3 + deg_w))
        for n in names:
            deg = ' '.join(scale_degree_labels(n))
            lines.append(f'{n.ljust(name_w)}   {deg.ljust(deg_w)}')
        lines.append('```')
        lines.append('')

    with open(out_path, 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines))
    print(f'wrote {out_path} ({len(SCALES)} scales)')


if __name__ == '__main__':
    main()
